services:
  - type: web
    name: learning-platform-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: NODE_ENV
        value: production
